[asterisk]
host=localhost
user=ameyodebug
secret=dacx
port=5038
confpath=/etc/asterisk

[callparams]
sipentity=simulator
context=test
extension=moh
callerid=01417119470
dynamic_from=no
dynamic_to=yes
to_prefix=0100
webhook=no
webhook_url=http://10.0.0.65:8081/v1/sip-trunk-webhook

